config/routes.rb
MicroBlog::Application.routes.draw do
  ActiveAdmin.routes(self)

  match '/users/auth/:provider/callback' => 'authorizations#create' 
  resources :authorizations, :only => [:index, :create]
  
  devise_for :users
  
  devise_scope :user do
    get "register", :to => "devise/registrations#new", :as => :register_user
    get "sign_in", :to => "devise/sessions#new", :as => :new_user_session
    delete "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  
  resources :users do
    resources :bleats
  end
  
  resources :bleats
  
  match '/trending/:tag' => 'search#trending'
  match '/search' => 'search#index'

  get "home/index"

  root :to => 'home#index'

end

app/views/shared/_errors.html.erb
<% if resource.errors.any? %>
	<div class="alert-box alert">
		<p>
		<%= I18n.t("errors.messages.not_saved",
                :count => resource.errors.count,
                :resource => resource.class.model_name.human.downcase) %>
         <ul class="errors">
    	<% resource.errors.full_messages.each do |error| %>
    		<li><%= error %></li>
    	<% end %>
    	</ul>
    	</p>
	</div>
<% end %>

app/views/shared/_menu.html.erb
<nav class="top-bar">
    <ul>
        <li class="name"><h1><a href="/">Bleater</a></h1></li>
        <li class="toggle-topbar"><a href="#"></a></li>
    </ul>
  
    <section>
        <ul class="left">
            <% if user_signed_in? %>
                <li class="has-dropdown">
                    <a href="#"><%= current_user.screen_name %></a>
            
                    <ul class="dropdown">
                        <li>
                            <%= link_to 'Profile', current_user %>
                        </li>
                        <% if current_user.admin? %>
                            <li>
                                <%= link_to "Admin", "/admin" %>
                            </li>
                        <% end %>
                        <li class="divider"></li>
                        <li>
                            <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
                        </li>
                    </ul>
                </li> 
            <% end %>
        </ul>
        <ul class="right">
            <li class="search has-button">
                <form method="get" action="/search">
                    <input id="search-box" name="q" type="text">
                    </input>
                    <button id="search-submit">
                        <i class="general foundicon-search">
                        </i>
                    </button>
                </form>
            </li>
            <% if user_signed_in? %>                
                <li>
                    <%= link_to 'Compose', new_bleat_path %>
                </li>       
            <% else %>
                <li>
                    <%= link_to 'Sign in', new_user_session_path %>
                </li>
                <li class="has-dropdown">
                    <a href="#">Sign in with</a>
            
                    <ul class="dropdown">
                        <% for provider in User.omniauth_providers %>
                            <li>
                                <%= link_to provider.to_s.titleize, user_omniauth_authorize_path(provider) %>
                            </li>
                        <% end %>
                    </ul>
            
                </li> 
            <% end %>
        </ul>
    </section>
</nav>